FORMAT: 1A
HOST: https://keepify-backend.herokuapp.com/

# Keepify

Backend services for Keepify.

## Authentication [/]

### Sign Up [POST /signup]
 Creates a new user.
+ Request (application/json)
    + Attributes
        + fname: `John` (string, required)
            User's first name.
        + lname: `Doe` (string, required)
            User's last name.
        + email: `ahmad@email.com` (string, required)
            User's email
        + password: `s3cur34nd1337` (string, required)
            User's password.
        + image_url: `/media/uploads/f2d57c07-363d-4a14-8ef9-615daf22ba60.png` (string)

    
+ Response 201 (application/json)
    + Attributes
        + status (Response Status, required)
        + user (User Info, required)
        + auth_token (string, required)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)

### Login [POST /login]
 Login.
+ Request (application/json)
    + Attributes
        + email: `ahmad@email.com` (string, required)
            User's email
        + password: `s3cur34nd1337` (string, required)
            User's password.
    
+ Response 200 (application/json)
    + Attributes
        + status (Response Status, required)
        + user (User Info, required)
        + auth_token (string, required)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)


## User [users/]

### Get current user info [GET /users/me]
 Gets the info of the current authenticated user.

+ Request (application/json)
    + Header
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU3MjI2NzcsImlhdCI6MTYxNTYzNjI3Nywic3ViIjoiMGM3Yzc2YmUtMjE4ZC00YWJiLTg3MWMtZjBiMmFjNmUyMmNlIn0.ek2ZabUJKhtZZY1gWZ_Vb2uadO-hzkHSzjmKXfzW8Ms
            
+ Response 200 (application/json)
    + Attributes
        + me (User Info, required)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)
    
### Update current user info [PUT /users/me]
 Update info of the current authenticated user.

+ Request (application/json)
    + Header
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU3MjI2NzcsImlhdCI6MTYxNTYzNjI3Nywic3ViIjoiMGM3Yzc2YmUtMjE4ZC00YWJiLTg3MWMtZjBiMmFjNmUyMmNlIn0.ek2ZabUJKhtZZY1gWZ_Vb2uadO-hzkHSzjmKXfzW8Ms
    + Attributes
        + fname: `John` (string, required)
            User's first name.
        + lname: `Doe` (string, required)
            User's last name.
        + email: `ahmad@email.com` (string, required)
            User's email
+ Response 200 (application/json)
    + Attributes
        + me (User Info, required)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)

### Get user info [GET /users?uid={uid}]
 Gets the info of a user. If no ID provided, gets ID from token.

+ Parameter
    + uid: `123e4567-e89b-12d3-a456-426655440000` (string, required)
        ID of a user.
+ Request (application/json)
    + Header
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
            
+ Response 200 (application/json)
    + Attributes
        + user (User Info, required)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)

## Dropzone [/dropzones]

### Query nearby dropzones [GET /dropzones?lat={lat}&lng={lng}]
 Queries the nearby dropzones via lat/lng.
+ Request (application/json)
    + Header
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
    
+ Parameter
    + lat: `39.945` (number, required)
        User's current location's latitude.
    + lng: `32.745` (number, required)
        User's current location's longitude.
        
+ Response 200 (application/json)
    + Attributes
        + status (Response Status, required)
        + data (array, required)
            + (Dropzone object)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)

### Get Dropzone by ID [GET /get-dropzone?id={id}]
 Retrieves a single dropzone via its id.
+ Request (application/json)
    + Header
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
    
+ Parameter
    + id: `123e4567-e89b-12d3-a456-426655440000` (number, required)
        The ID of the dropzone to be retrieved.
        
+ Response 200 (application/json)
    + Attributes
        + status (Response Status, required)
        + data (Dropzone object, required)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)

## Transaction [/transactions]

### Query single Transaction [GET /transactions?uuid={uuid}]
 Query single Transaction using provided id
+ Request (application/json)
    + Header
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
    
+ Parameter
    + uuid: `123e4567-e89b-12d3-a456-426655440000` (string, required)
       
        
+ Response 200 (application/json)
    + Attributes
        + status (Response Status, required)
        + data (Transaction, required)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)


### Query multiple Transactions [GET /transactions?status={status}&before={before}&after={after}]
 Query multiple Transactions with filters like status, and before and after specific data ranges
+ Request (application/json)
    + Header
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
    
+ Parameter
    + status: `COMPLETED` (string, required)
    + before: `11:00:59 20/11/2021 0800` (required)  
    + after: `11:00:59 20/11/2021 0800` (required)
        
+ Response 200 (application/json)
    + Attributes
        + status (Response Status, required)
        + data (array, required)
            + (Transaction)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)
    

### Create a Transaction [POST /transactions]
 Create a Transaction
+ Request (application/json)
    + Header
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
    + Attributes
        + host_token: `123e4567-e89b-12d3-a456-426655440000` (string, required)
            Vertification token for the host
        + dropzone_id: `123e4567-e89b-12d3-a456-426655440000` (string, required)
        + reservation_start: `11:00:59 20/11/2021 0800` (required) 
        + reservation_end: `11:00:59 20/11/2021 0800` (required) 
        + status: `CREATED` (string, required) 
        + cost: 5 (number, required) 
    
+ Response 200 (application/json)
    + Attributes
        + status (Response Status, required)
        + message: Successfully created. (string, required)
        + transaction (Transaction, required)


+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)   


## Media [/media]

### Upload image [POST /media/image]
 Upload an image

+ Request (multipart/form-data; boundary=---BOUNDARY)

        -----BOUNDARY
        Content-Disposition: form-data; name="image[file]"; filename="image.jpg"
        Content-Type: image/jpeg
        Content-Transfer-Encoding: base64

        /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
        HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
        MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
        AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
        AAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AD//Z
        -----BOUNDARY

+ Response 201 (application/json)
    + Attributes
        + location: `url` (string, required)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)
 

### Get image [GET /uploads?{name}]
 Get the uploaded image
    
+ Parameter
    + name: `123e4567-e89b-12d3-a456-426655440000` (number, required)
        The name of the image to be retrieved.
        
+ Response 200 (application/json)

+ Response 400 (application/json)
    + Attributes (Failure Response)
+ Response 401 (application/json)
    + Attributes (Failure Response)
+ Response 404 (application/json)
    + Attributes (Failure Response)
+ Response 500 (application/json)
    + Attributes (Failure Response)
    
# Data Structures

## User Info (object)
+ id: `123e4567-e89b-12d3-a456-426655440000` (string, required)
+ fname: `Joe` (string, required)
+ lname: `Warosa` (string, required)
+ email: `email@email.com` (string, required)
+ role: `0` (string, required)
+ image_url: `"/media/uploads/f2d57c07-363d-4a14-8ef9-615daf22ba60.png"` (string)

## Dropzone object (object)
+ id: `123e4567-e89b-12d3-a456-426655440000` (string, required)
    ID.
+ name: `Dropzone 1` (string, required)
    Name.
+ thumbnail: `somelink.com/image.png` (string, required)
    thumbnail.
+ type: `Warehouse` (string, required)
    type.
+ services: `storing`, `shipping` (array, required)
    services.
    + (string)
+ rating: `3.8` (number, required)
    rating.
+ unit: `$` (string, required)
    unit.
+ rate: `5.5` (number, required)
    rate.
+ location: (object, required)
    + lat: `40.23` (number, required)
        Latitude of the dropzone location.
    + lng: `123.45` (number, required)
        Longitude of the dropzone location.
+ host: (User Info, required)
    The host of the dropzone

## Transaction (object)
+ id: `123e4567-e89b-12d3-a456-426655440000` (string, required)
+ user: (User Info, required)
+ dropzone: (Dropzone object, required)
+ creation_time: `11:00:59 20/11/2021 0800` (required)
+ reservation_start: `11:00:59 20/11/2021 0800` (required)
+ reservation_end: `11:00:59 20/11/2021 0800` (required)
+ status: `COMPLETED` (string, required)
+ cost: 25 (number, required)
+ host_token: `24asd21-asda-12dssds-23` (string, required)

## Response Status (enum[string])
+ success
+ failure

## Failure Response (object)
+ status (Response Status, required)
+ error: Error message (string, required)